### DISCUSSION TITLE
a practise , waiting online, thx!

### DISCUSSION THREAD

**Discussion by yuanrengui** [bytedance/g3#123] [General]
hi ,
   I need a top with two g3proxy -s ,  I would like to a pratice configure about .yaml .  Can you instruct me to complish it. 
 
my requirement:
   proxy client --- g3proxy(1) ---- firewall---- g3proxy(2) ---- internet.

my issue is how I can configure the g3proxy(1) to forward my require traffic (from client) to g3proxy(2) , then enter the internet.

Best Regards,
Ryan

**Comment by yuanrengui** [comment]
hints:  I want to forward traffice for http/https/socks protocol through proxy !

**Comment by zh-jq-b** [comment]
proxy2 开一个 socks proxy server，示例参考 https://github.com/bytedance/g3/blob/master/g3proxy/examples/simple_socks_proxy/g3proxy.yaml
proxy1 开一个 http proxy server + socks proxy server，指向一个 proxy_socks5 escaper，这个escaper指向 proxy2 的socks proxy地址，示例参考 https://github.com/bytedance/g3/blob/master/g3proxy/examples/chain_socks_proxy/g3proxy.yaml ，需要自己增加一个http proxy server配置

**Reply by yuanrengui** [reply]
thx，can you give me a .yaml practise file for proxy1 ?

**Reply by zh-jq-b** [reply]
```yaml
---
server:
  - name: socks
    escaper: socks
    type: socks_proxy
    listen: "[::]:1080"
    enable_udp_associate: true
  - name: http
    escaper: socks
    type: http_proxy
    listen: "[::]:3128"

resolver:
  - name: default
    type: c-ares
    server: 223.5.5.5

escaper:
  - name: socks
    type: proxy_socks5
    proxy_addr: "1.2.3.4:1080"
```
