### ISSUE TITLE
ICAP issues

### ISSUE THREAD

**Issue by mspublic** [bytedance/g3#165]
I have g3 running and have started testing ICAP integration but have run into weird issues. 

When I start g3 it sends an initial OPTIONS to the ICAP server. But after that it does not send reqmod/respmod to the server even with the ratio set to 1. If I turn down the ratio to .5 it will *occasionally* send a Icap res/req. Maybe 1/100. I am wondering if it could be an issue with the ratio code. I have not seen any errors in the g3 logs.

I have started trying to track down where the issue might be but I wanted to file a ticket in case you might know or have suggestions. I will also add more general logging output to the Icap while going through this then file a PR.

I am using the open source icapeg server for testing. Below is my config

```
auditor:
  - name: default
    protocol_inspection: {} # Enable protocol recognition, use default parameters
    tls_cert_generator: {}  # Enable TLS hijacking, use default parameters
    tls_interception_client: {} # Can configure proxy to target address TLS connection parameters
    h1_interception: {}         # HTTP/1.0 parsing parameters
    h2_interception: {}         # HTTP/2 parsing parameters
    icap_reqmod_service: icap://127.0.0.1:1344/echo   # ICAP REQMOD service configuration
    icap_respmod_service: icap://127.0.0.1:1344/echo # ICAP RESPMOD service configuration
    application_audit_ratio: 1.0 
```
