### ISSUE TITLE
TLS client protocol does not seem to be properly set from config

### ISSUE THREAD

**Issue by mspublic** [bytedance/g3#280]
I am trying to set the tls client protocol for outgoing requests (that are intercepted) the value does not appear to be respected. For example I set it to tls1.2 but when I test with https://browserleaks.com/tls it always shows 1.3. This happens with openssl and boringssl. Example config:

```  
- name: proxy
    escaper: default
    auditor: default
    type: http_proxy
    listen:
      address: "[::]:4000"
    tls_client:
      protocol: tls1.2
```

**Comment by zh-jq-b** [comment]
The tls_client config here only affect https_forward requests. Currently we don't support set outgoing tls protocol versions in tls interception.

**Comment by zh-jq** [comment]
To support custom TLS client config for HTTP CONNECT requests, you need to use user-site config.
Add the following to `main.yaml`:
```yaml
user-group:
 - name: default
   anonymous_user:
     audit:
       enable_protocol_inspection: true
     explicit_sites:
       - exact_match: browserleaks.com
         tls_client:
           protocol: tls1.2
```
And you need to change the `http_proxy` server config to include `user-group: default`.
All requests without user auth information will match that anonymous_user config.
