### ISSUE TITLE
4to6 正向代理

### ISSUE THREAD

**Issue by newcoderlife** [bytedance/g3#340]
如题，我的代理服务器有 v4/v6 双栈地址，内网其它服务器只有 v4 单栈。我希望内网其它服务器通过代理服务器的 v6 访问外部 HTTP/HTTPS 服务。请问 g3proxy 当前可以实现 4to6 的正向代理吗。

我的尝试：
```
log: journal

server:
  - name: intelli
    type: intelli_proxy
    listen: "[::]:8080"
    http_server: http
    socks_server: socks

  - name: http
    escaper: 4to6
    type: http_proxy
    listen:
      address: "127.0.0.1:8081"
    tls_client: { }

  - name: socks
    escaper: 4to6
    type: socks_proxy
    listen:
      address: "127.0.0.1:8082"
    enable_udp_associate: true
    udp_socket_buffer: 512K

  - name: sni
    escaper: 4to6
    type: sni_proxy
    listen:
      address: "[::]:8083"

escaper:
  - name: 4to6
    type: direct_fixed
    resolver: default
    no_ipv4: true
    resolve_strategy: IPv6Only

resolver:
  - name: default
    type: c-ares
    server: 1.1.1.1
```

访问方式：`curl --socks5 localhost:8080 https://www.google.com/`
错误日志：`gateway g3proxy[83727]: forbidden by rule: target ip blocked`
