### ISSUE TITLE
How to proxy-chain to a server on the open internet that uses basic authentication?

### ISSUE THREAD

**Issue by webhype** [bytedance/g3#406]
I fully read through the user guide at https://github.com/bytedance/g3/blob/master/g3proxy/UserGuide.en_US.md and didn't see this mentioned:

When proxy-chaining to an external proxy in the wild, whose proxy connect URL would be:

`http://myuser:mypass@12.34.56.78:8088`

where and how do I define in the `escaper` (I assume that's where it has be defined), the username and password part of the external HTTP proxy?

What I have tried, guessing there has to be something like `username` and `password` settable in the escaper, I modified the basic example at https://github.com/bytedance/g3/blob/master/g3proxy/examples/chain_proxy_protocol/g3proxy.yaml:

```
escaper:
  - name: proxy_pp1
    type: proxy_http
    proxy_addr: "12.34.56.78:8088"
    use_proxy_protocol: 1
    username: myuser
    password: mypass
```
Not surprisingly, `./g3proxy` fails with error:
```
Error: failed to load config, opts: ProcArgs { daemon_config: DaemonArgs { with_systemd
: false, daemon_mode: false, verbose_level: 0, process_name: "g3proxy", pid_file: None,
 test_config: false }, output_graphviz_graph: false, output_mermaid_graph: false, outpu
t_plantuml_graph: false }

Caused by:
    0: failed to parse value of key escaper
    1: value is an array, with 3 objects
    2: #0: failed to load map {String("name"): String("proxy_pp1"), String("type"): Str
ing("proxy_http"), String("proxy_addr"): String("12.34.56.78:8088"), String("use_prox
y_protocol"): Integer(1), String("username"): String("myuser"), String("password"):
 String("mypass")}
    3: failed to parse value of key username
    4: invalid key username
```
How do I authenticate with the external HTTP proxy?

**Comment by zh-jq** [comment]
you can find the detail configuration。docs here https://github.com/bytedance/g3/tree/master/g3proxy/doc

**Comment by zh-jq** [comment]
Thanks for your suggestions, they are valuable for us.

You are right, I will try to publish the sphinx generated html docs on *Read the Docs* or *Github Pages*, it's better than do nothing.

The main focus of the g3proxy 1.11 development cycle will be on test cases and documents. The documentation part will be a big challenge for us.

Thanks for your suggestions again, they are helpful.

**Comment by zh-jq** [comment]
@webhype I have added a test repo here https://zh-jq-g3.readthedocs.io/en/latest/configuration/index.html, you can use this before I finish the final official doc site.

**Comment by webhype** [comment]
Thanks, I really don't want to be "Negative Nilly" and I wrote my suggestions in order to help the community adoption. Here's what worked for me to generate the docs on Mac OS, in case it helps someone:
```
brew install sphinx-doc
echo 'export PATH="/opt/homebrew/opt/sphinx-doc/bin:$PATH"' >> ~/.bash_profile
export PATH="/opt/homebrew/opt/sphinx-doc/bin:$PATH"
cd ~/projects/g3/g3proxy/doc/
sphinx-build . _build
```
Also, here's a fully working example `g3proxy` `.yaml` file for proxy-chaining to two remote, simple-authenticated proxy in the wild:
```
server:
  - name: http1
    escaper: proxy_pp1
    type: http_proxy
    listen:
      address: "127.0.0.1:31001"
  - name: http2
    escaper: proxy_pp2
    type: http_proxy
    listen:
      address: "127.0.0.1:31002"
  - name: http0
    escaper: default
    type: http_proxy

resolver:
  - name: default
    type: c-ares
    server: 8.8.8.8 # Put DNS server of your choice here

# See ~/mm/g3/g3proxy/doc/_build/configuration/escapers/index.html
escaper:
  - name: proxy_pp1
    type: proxy_http
    proxy_addr: "12.34.56.78:8080"
    proxy_username: "myUser1"
    proxy_password: "myPass1"
  - name: proxy_pp2
    type: proxy_http
#    proxy_addr: "[::1]:3132"
    proxy_addr: "98.76.54.32:8081"
    proxy_username: "myUser2"
    proxy_password: "myPass2"
  - name: default
    type: direct_fixed
    resolver: default

log: stdout # remove this to stop verbose logging of what's happening
```
