### ISSUE TITLE
Dynamically replacing endpoint via query parameter

### ISSUE THREAD

**Issue by winstxnhdw** [bytedance/g3#608]
This is quite a specific use-case but I am wondering if there are plans to support this kind of use case.

```bash
curl http://g3-proxy-server/?endpoint="https://github.com/bytedance/g3"
```

I understand that `g3proxy` is meant to be used with the `HTTP_PROXY` environment variable but I can think of a few cases where the user will not have access to the environment that is forwarding that request.

For example, I have a Grafana instance which I have no immediate control over. The Grafana instance can only send alerts to contact points that are not SSL certified but I have an endpoint that requires SSL certification. In such a case, I would like to have g3 proxy the request from Grafana without hard-coding the endpoints on my g3 proxy server.

**Comment by zh-jq** [comment]
Will this work for you?
`http://{proxy_host}/.well-known/easy-proxy/https/{target_host}/{target_port}/`
It will become
`https://{target_host}:{target_port}/`
and keep the following path and queries

**Comment by winstxnhdw** [comment]
Yeap, perfect.

**Comment by winstxnhdw** [comment]
Can't wait! Thank you. I'll leave some benchmarks after trying it.

**Comment by winstxnhdw** [comment]
Hi @zh-jq,

I am getting status code 400

```bash
curl -v http://localhost:10086/.well-known/easy-proxy/https/github.com/80/bytedance/g3
```

```bash
* Host localhost:10086 was resolved.
* IPv6: ::1
* IPv4: 127.0.0.1
*   Trying [::1]:10086...
* Connected to localhost (::1) port 10086
* using HTTP/1.x
> GET /.well-known/easy-proxy/https/github.com/80/bytedance/g3 HTTP/1.1
> Host: localhost:10086
> User-Agent: curl/8.13.0
> Accept: */*
>
* Request completely sent off
< HTTP/1.1 400 Bad Request
< Content-Type: text/html
< Content-Length: 138
< Connection: Close
<
<html>
<head><title>400 Bad Request</title></head>
<body>
<div style="text-align: center;"><h1>400 Bad Request</h1></div>
</body>
</html>
* shutting down connection #477 
```

```yaml
runtime:
  thread_number: 1

log: stdout

server:
  - name: test
    escaper: default
    type: http_proxy
    listen:
      address: "[::]:10086"
    tls_client: { }
    local_server_name: 0.0.0.0
    tcp_sock_speed_limit: 100M

resolver:
  - name: default
    type: c-ares

escaper:
  - name: default
    type: direct_fixed
    no_ipv6: true
    resolver: default
    resolve_strategy: IPv4Only
    tcp_sock_speed_limit: 80M
    udp_sock_speed_limit: 10M
    egress_network_filter:
      default: allow
      allow:
        - 0.0.0.0
```

**Comment by zh-jq** [comment]
@winstxnhdw you can delete the local_server_name config or set it to the same one in the curl Host header.
And the port in your url should be 443 instead of 80.

**Comment by winstxnhdw** [comment]
Hmm... Doesn't seem to be able to make the SSL connection. Does g3proxy respect the `HTTP_PROXY` and `HTTPS_PROXY` environment variables?

```bash
Apr 19 20:28:45.495 INFO c_rd_bytes: 110, c_wr_bytes: 258, client_addr: 172.18.0.1:57850, daemon_name: , escaper: default, log_type: Task, method: GET, next_bound_addr: 172.18.0.2:42752, next_peer_addr: 20.26.156.215:443, origin_status: 0, pid: 7, pipeline_wait: 22.046µs, r_rd_bytes: 0, r_wr_bytes: 0, reason: UpstreamTlsHandshakeTimeout, reuse_connection: false, rsp_status: 525, server_addr: 172.18.0.2:10086, server_name: test, server_type: HttpProxy, stage: Connecting, start_at: 2025-04-19T20:28:35.428400Z, task_event: Finished, task_id: de6bb9e01d5c11f08ec05188687551a6, task_type: HttpForward, tcp_connect_spend: 65.409ms, tcp_connect_tries: 1, total_time: 10.067s, upstream: github.com:443, uri: https://github.com:443/bytedance/g3, wait_time: 41.487µs, upstream tls handshake timeout

Apr 19 20:28:45.495 INFO daemon_name: , escape_type: TlsHandshake, escaper_name: default, escaper_type: DirectFixed, log_type: Escape, next_bound_addr: 172.18.0.2:42752, next_peer_addr: 20.26.156.215:443, pid: 7, task_id: de6bb9e01d5c11f08ec05188687551a6, tls_application: HttpForward, tls_name: github.com, tls_peer: github.com:443, upstream: github.com:443, upstream tls handshake timed out
```

**Comment by zh-jq** [comment]
> Hmm... Doesn't seem to be able to make the SSL connection. Does g3proxy respect the `HTTP_PROXY` and `HTTPS_PROXY` environment variables?
> 

No. You need to use proxy_http or other proxy_* escapers if you want chain proxy.

**Comment by winstxnhdw** [comment]
I added the proxy escaper but it is still giving me a 525 SSL Handshake Failed.

```yaml
runtime:
  thread_number: 1

log: stdout

server:
  - name: test
    escaper: http
    type: http_proxy
    listen:
      address: "[::]:10086"

resolver:
  - name: default
    type: c-ares

escaper:
  - name: http
    type: proxy_http
    proxy_addr: proxy.local:3000
    no_ipv6: true
    resolver: default
    resolve_strategy: IPv4Only
    tcp_sock_speed_limit: 80M
```

```bash
curl -v http://localhost:10086/.well-known/easy-proxy/https/github.com/443/bytedance/g3
```
